// Generated by scripts/build_sim_lab_index.py — do not edit by hand.
// Re-run that script when sim-lab scenarios are added or renamed.
window.SIM_LAB_SCENARIOS = [
  {
    "code": "B-T1-01",
    "category": "Behavioral",
    "tier": "T1",
    "name": "Excited Delirium with Occult Hypoglycemia",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/B-T1-01/"
  },
  {
    "code": "B-T1-02",
    "category": "Behavioral",
    "tier": "T1",
    "name": "Hypothermia, Mild to Moderate",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/B-T1-02/"
  },
  {
    "code": "B-T2-01",
    "category": "Behavioral",
    "tier": "T2",
    "name": "Agitated Patient with Occult Head Injury",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/B-T2-01/"
  },
  {
    "code": "B-T2-02",
    "category": "Behavioral",
    "tier": "T2",
    "name": "Heat Stroke Requiring Aggressive Cooling",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/B-T2-02/"
  },
  {
    "code": "B-T3-01",
    "category": "Behavioral",
    "tier": "T3",
    "name": "Hypothermic Cardiac Arrest",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/B-T3-01/"
  },
  {
    "code": "B-T3-02",
    "category": "Behavioral",
    "tier": "T3",
    "name": "Excited Delirium Progressing to Sudden Cardiac Arrest",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/B-T3-02/"
  },
  {
    "code": "C-T1-01",
    "category": "Cardiac",
    "tier": "T1",
    "name": "Stable Angina vs. ACS — Resolved Exertional Chest Pain",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T1-01/"
  },
  {
    "code": "C-T1-02",
    "category": "Cardiac",
    "tier": "T1",
    "name": "New-Onset Atrial Fibrillation with Adequate Rate",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T1-02/"
  },
  {
    "code": "C-T1-03",
    "category": "Cardiac",
    "tier": "T1",
    "name": "Hypertensive Crisis without End-Organ Symptoms",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T1-03/"
  },
  {
    "code": "C-T1-04",
    "category": "Cardiac",
    "tier": "T1",
    "name": "Syncope with Cardiac Etiology",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T1-04/"
  },
  {
    "code": "C-T1-05",
    "category": "Cardiac",
    "tier": "T1",
    "name": "CHF Exacerbation, Early Presentation",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T1-05/"
  },
  {
    "code": "C-T1-06",
    "category": "Cardiac",
    "tier": "T1",
    "name": "Symptomatic Bradycardia, Medication-Induced",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T1-06/"
  },
  {
    "code": "C-T1-07",
    "category": "Cardiac",
    "tier": "T1",
    "name": "Chest Pain with Non-Cardiac Cause",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T1-07/"
  },
  {
    "code": "C-T2-01",
    "category": "Cardiac",
    "tier": "T2",
    "name": "STEMI with Complicating History — Anaphylactic ASA Allergy",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T2-01/"
  },
  {
    "code": "C-T2-02",
    "category": "Cardiac",
    "tier": "T2",
    "name": "SVT Not Responding to Vagal Maneuvers",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T2-02/"
  },
  {
    "code": "C-T2-03",
    "category": "Cardiac",
    "tier": "T2",
    "name": "Acute Pulmonary Edema Requiring Aggressive Management",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T2-03/"
  },
  {
    "code": "C-T2-04",
    "category": "Cardiac",
    "tier": "T2",
    "name": "Unstable A-Fib with RVR",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T2-04/"
  },
  {
    "code": "C-T2-05",
    "category": "Cardiac",
    "tier": "T2",
    "name": "Acute Inferior STEMI with Right-Sided Involvement",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T2-05/"
  },
  {
    "code": "C-T2-06",
    "category": "Cardiac",
    "tier": "T2",
    "name": "Second-Degree Type II Progressing to Third-Degree Block",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T2-06/"
  },
  {
    "code": "C-T2-07",
    "category": "Cardiac",
    "tier": "T2",
    "name": "Post-ROSC Management",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T2-07/"
  },
  {
    "code": "C-T2-08",
    "category": "Cardiac",
    "tier": "T2",
    "name": "Cocaine-Associated Chest Pain",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T2-08/"
  },
  {
    "code": "C-T3-01",
    "category": "Cardiac",
    "tier": "T3",
    "name": "Witnessed V-Fib Arrest — Shock First",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T3-01/"
  },
  {
    "code": "C-T3-02",
    "category": "Cardiac",
    "tier": "T3",
    "name": "V-Tach Deterioration to V-Fib Arrest",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T3-02/"
  },
  {
    "code": "C-T3-03",
    "category": "Cardiac",
    "tier": "T3",
    "name": "PEA Arrest with Reversible Cause",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T3-03/"
  },
  {
    "code": "C-T3-04",
    "category": "Cardiac",
    "tier": "T3",
    "name": "Cardiogenic Shock with Deterioration to Arrest",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T3-04/"
  },
  {
    "code": "C-T3-05",
    "category": "Cardiac",
    "tier": "T3",
    "name": "Asystole/Agonal Rhythm with DNR Confusion",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T3-05/"
  },
  {
    "code": "M-T1-01",
    "category": "Medical",
    "tier": "T1",
    "name": "Hypoglycemia Presenting as Altered Mental Status",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/M-T1-01/"
  },
  {
    "code": "M-T1-02",
    "category": "Medical",
    "tier": "T1",
    "name": "CVA/Stroke with Clear Onset Time",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/M-T1-02/"
  },
  {
    "code": "M-T1-03",
    "category": "Medical",
    "tier": "T1",
    "name": "Simple Febrile Seizure (Adult), Post-Ictal",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/M-T1-03/"
  },
  {
    "code": "M-T1-04",
    "category": "Medical",
    "tier": "T1",
    "name": "Allergic Reaction without Anaphylaxis",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/M-T1-04/"
  },
  {
    "code": "M-T1-05",
    "category": "Medical",
    "tier": "T1",
    "name": "Diabetic Ketoacidosis, Early Recognition",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/M-T1-05/"
  },
  {
    "code": "M-T2-01",
    "category": "Medical",
    "tier": "T2",
    "name": "Opioid Overdose with Complicated Airway",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/M-T2-01/"
  },
  {
    "code": "M-T2-02",
    "category": "Medical",
    "tier": "T2",
    "name": "Stroke Mimic",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/M-T2-02/"
  },
  {
    "code": "M-T2-03",
    "category": "Medical",
    "tier": "T2",
    "name": "Seizure Progressing to Status Epilepticus",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/M-T2-03/"
  },
  {
    "code": "M-T2-04",
    "category": "Medical",
    "tier": "T2",
    "name": "Tricyclic Antidepressant Overdose",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/M-T2-04/"
  },
  {
    "code": "M-T2-05",
    "category": "Medical",
    "tier": "T2",
    "name": "Sepsis with Ambiguous Source",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/M-T2-05/"
  },
  {
    "code": "M-T3-01",
    "category": "Medical",
    "tier": "T3",
    "name": "Polysubstance Overdose with Hemodynamic Collapse",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/M-T3-01/"
  },
  {
    "code": "M-T3-02",
    "category": "Medical",
    "tier": "T3",
    "name": "Status Epilepticus Refractory to Benzodiazepines",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/M-T3-02/"
  },
  {
    "code": "M-T3-03",
    "category": "Medical",
    "tier": "T3",
    "name": "Severe Sepsis Progressing to Septic Shock",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/M-T3-03/"
  },
  {
    "code": "M-T3-04",
    "category": "Medical",
    "tier": "T3",
    "name": "Beta-Blocker/Calcium Channel Blocker Overdose",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/M-T3-04/"
  },
  {
    "code": "P-T1-01",
    "category": "Pediatric",
    "tier": "T1",
    "name": "Febrile Seizure in a Toddler",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/P-T1-01/"
  },
  {
    "code": "P-T1-02",
    "category": "Pediatric",
    "tier": "T1",
    "name": "Pediatric Asthma Exacerbation — 7yo Responds to DuoNeb",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/P-T1-02/"
  },
  {
    "code": "P-T1-03",
    "category": "Pediatric",
    "tier": "T1",
    "name": "Infant with RSV / Bronchiolitis — Assessment-Driven Supportive Care",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/P-T1-03/"
  },
  {
    "code": "P-T2-01",
    "category": "Pediatric",
    "tier": "T2",
    "name": "Croup with Worsening Stridor",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/P-T2-01/"
  },
  {
    "code": "P-T2-02",
    "category": "Pediatric",
    "tier": "T2",
    "name": "Pediatric Dehydration with Compensated Shock",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/P-T2-02/"
  },
  {
    "code": "P-T2-03",
    "category": "Pediatric",
    "tier": "T2",
    "name": "Pediatric SVT",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/P-T2-03/"
  },
  {
    "code": "P-T2-04",
    "category": "Pediatric",
    "tier": "T2",
    "name": "Foreign Body Airway Obstruction, Progressing",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/P-T2-04/"
  },
  {
    "code": "P-T3-01",
    "category": "Pediatric",
    "tier": "T3",
    "name": "Pediatric Cardiac Arrest, Shockable Rhythm",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/P-T3-01/"
  },
  {
    "code": "P-T3-02",
    "category": "Pediatric",
    "tier": "T3",
    "name": "Pediatric Respiratory Failure to Arrest",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/P-T3-02/"
  },
  {
    "code": "P-T3-03",
    "category": "Pediatric",
    "tier": "T3",
    "name": "Critically Ill Neonate/Infant, Undiagnosed",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/P-T3-03/"
  },
  {
    "code": "R-T1-01",
    "category": "Respiratory",
    "tier": "T1",
    "name": "Asthma Exacerbation, Moderate — Adult Responds to DuoNeb",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/R-T1-01/"
  },
  {
    "code": "R-T1-02",
    "category": "Respiratory",
    "tier": "T1",
    "name": "COPD Exacerbation vs. CHF — 72yo with Dual History",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/R-T1-02/"
  },
  {
    "code": "R-T1-03",
    "category": "Respiratory",
    "tier": "T1",
    "name": "Upper Airway Obstruction, Partial — Evolving Allergic Airway Edema",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/R-T1-03/"
  },
  {
    "code": "R-T1-04",
    "category": "Respiratory",
    "tier": "T1",
    "name": "Hyperventilation with Underlying Cause — Early DKA Masquerading as Panic Attack",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/R-T1-04/"
  },
  {
    "code": "R-T1-05",
    "category": "Respiratory",
    "tier": "T1",
    "name": "Pneumonia Presentation — Adult with Early Sepsis",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/R-T1-05/"
  },
  {
    "code": "R-T2-01",
    "category": "Respiratory",
    "tier": "T2",
    "name": "Severe Asthma, Failing First-Line Treatment",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/R-T2-01/"
  },
  {
    "code": "R-T2-02",
    "category": "Respiratory",
    "tier": "T2",
    "name": "COPD with Respiratory Acidosis",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/R-T2-02/"
  },
  {
    "code": "R-T2-03",
    "category": "Respiratory",
    "tier": "T2",
    "name": "Anaphylaxis with Airway Compromise",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/R-T2-03/"
  },
  {
    "code": "R-T2-04",
    "category": "Respiratory",
    "tier": "T2",
    "name": "Aspiration Event in Altered Patient",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/R-T2-04/"
  },
  {
    "code": "R-T2-05",
    "category": "Respiratory",
    "tier": "T2",
    "name": "Acute Asthma Progressing to Quiet Chest",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/R-T2-05/"
  },
  {
    "code": "R-T3-01",
    "category": "Respiratory",
    "tier": "T3",
    "name": "Respiratory Failure Requiring Advanced Airway",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/R-T3-01/"
  },
  {
    "code": "R-T3-02",
    "category": "Respiratory",
    "tier": "T3",
    "name": "Failed First Airway Attempt — Septic Pneumonia with Predicted Difficult Airway",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/R-T3-02/"
  },
  {
    "code": "R-T3-03",
    "category": "Respiratory",
    "tier": "T3",
    "name": "Severe Anaphylaxis Progressing to Arrest",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/R-T3-03/"
  },
  {
    "code": "R-T3-04",
    "category": "Respiratory",
    "tier": "T3",
    "name": "Submersion/Drowning with Hypothermic Cardiac Arrest",
    "url": "https://matc-ems.github.io/scenarios/sim-lab/R-T3-04/"
  }
];
