"""Unit tests for scripts/build_sim_lab_index.py."""
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))

import build_sim_lab_index as b


class TestParseCode(unittest.TestCase):
    def test_valid_code(self):
        self.assertEqual(b.parse_code("C-T1-01"), ("C", "T1", "01"))

    def test_valid_code_other_category_and_tier(self):
        self.assertEqual(b.parse_code("R-T3-04"), ("R", "T3", "04"))

    def test_non_code_returns_none(self):
        self.assertIsNone(b.parse_code("index.html"))

    def test_bad_tier_returns_none(self):
        self.assertIsNone(b.parse_code("C-T4-01"))

    def test_bad_category_letter_returns_none(self):
        self.assertIsNone(b.parse_code("X-T1-01"))


class TestCategoryName(unittest.TestCase):
    def test_known_letters(self):
        self.assertEqual(b.category_name("B"), "Behavioral")
        self.assertEqual(b.category_name("C"), "Cardiac")
        self.assertEqual(b.category_name("M"), "Medical")
        self.assertEqual(b.category_name("P"), "Pediatric")
        self.assertEqual(b.category_name("R"), "Respiratory")

    def test_unknown_letter_falls_back_to_letter(self):
        self.assertEqual(b.category_name("Z"), "Z")


class TestScenarioUrl(unittest.TestCase):
    def test_url(self):
        self.assertEqual(
            b.scenario_url("C-T1-01"),
            "https://matc-ems.github.io/scenarios/sim-lab/C-T1-01/",
        )


class TestBuildEntry(unittest.TestCase):
    def test_happy_path(self):
        self.assertEqual(
            b.build_entry("C-T1-01", "Chest Pain"),
            {
                "code": "C-T1-01",
                "category": "Cardiac",
                "tier": "T1",
                "name": "Chest Pain",
                "url": "https://matc-ems.github.io/scenarios/sim-lab/C-T1-01/",
            },
        )

    def test_none_name_falls_back_to_code(self):
        self.assertEqual(b.build_entry("R-T2-03", None)["name"], "R-T2-03")

    def test_invalid_code_raises(self):
        with self.assertRaises(ValueError):
            b.build_entry("index.html", "x")


class TestSortKey(unittest.TestCase):
    def test_sorts_by_category_then_tier_then_code(self):
        entries = [
            {"category": "Cardiac", "tier": "T2", "code": "C-T2-01"},
            {"category": "Behavioral", "tier": "T1", "code": "B-T1-01"},
            {"category": "Cardiac", "tier": "T1", "code": "C-T1-02"},
            {"category": "Cardiac", "tier": "T1", "code": "C-T1-01"},
        ]
        ordered = [e["code"] for e in sorted(entries, key=b.sort_key)]
        self.assertEqual(ordered, ["B-T1-01", "C-T1-01", "C-T1-02", "C-T2-01"])


class TestRenderJs(unittest.TestCase):
    def test_has_header_and_assignment(self):
        out = b.render_js([])
        self.assertIn("Generated by scripts/build_sim_lab_index.py", out)
        self.assertIn("window.SIM_LAB_SCENARIOS = [", out)
        self.assertTrue(out.endswith("];\n"))

    def test_includes_entry_data(self):
        entry = b.build_entry("C-T1-01", "Chest Pain")
        out = b.render_js([entry])
        self.assertIn('"code": "C-T1-01"', out)
        self.assertIn('"name": "Chest Pain"', out)


if __name__ == "__main__":
    unittest.main()
