"""Generate sim-lab/scenarios.js from the matc-ems/scenarios repo.

Reads each sim-lab scenario's unified.json for its display name and emits a
committed JS data file that the /sim-lab page renders. Standard library only.

Run from the matc-ems-site repo root:
    python3 scripts/build_sim_lab_index.py [--scenarios-dir ../scenarios]
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

# Category letter -> display name (matc-ems/scenarios convention).
CATEGORIES = {
    "B": "Behavioral",
    "C": "Cardiac",
    "M": "Medical",
    "P": "Pediatric",
    "R": "Respiratory",
}

# Scenario folder code: <category letter>-T<tier 1-3>-<sequence digits>.
CODE_RE = re.compile(r"^([BCMPR])-T([123])-(\d+)$")

GITHUB_PAGES_BASE = "https://matc-ems.github.io/scenarios/sim-lab"

# Fixed category display order.
_CATEGORY_ORDER = list(CATEGORIES.values())


def parse_code(folder_name):
    """Parse a scenario folder name into (category_letter, tier, sequence).

    Returns None when the name is not a valid scenario code, so callers can
    skip stray files/directories (e.g. the sim-lab/index.html beside them).
    """
    m = CODE_RE.match(folder_name)
    if not m:
        return None
    letter, tier_digit, seq = m.groups()
    return letter, f"T{tier_digit}", seq


def category_name(letter):
    """Map a category letter to its display name; unknown letters return as-is."""
    return CATEGORIES.get(letter, letter)


def scenario_url(code):
    """The GitHub Pages URL of a scenario's interactive player."""
    return f"{GITHUB_PAGES_BASE}/{code}/"


def build_entry(folder_name, name):
    """Build one scenarios.js entry from a folder name and display name.

    Raises ValueError if folder_name is not a valid scenario code. A falsy
    `name` (None or empty) falls back to the code.
    """
    parsed = parse_code(folder_name)
    if parsed is None:
        raise ValueError(f"not a scenario code: {folder_name!r}")
    letter, tier, _seq = parsed
    return {
        "code": folder_name,
        "category": category_name(letter),
        "tier": tier,
        "name": name or folder_name,
        "url": scenario_url(folder_name),
    }


def sort_key(entry):
    """Sort entries by category (fixed order), then tier, then code."""
    category = entry["category"]
    cat_idx = (
        _CATEGORY_ORDER.index(category)
        if category in _CATEGORY_ORDER
        else len(_CATEGORY_ORDER)
    )
    return (cat_idx, entry["tier"], entry["code"])


def render_js(entries):
    """Render entries as the contents of sim-lab/scenarios.js."""
    body = json.dumps(entries, indent=2, ensure_ascii=False)
    return (
        "// Generated by scripts/build_sim_lab_index.py — do not edit by hand.\n"
        "// Re-run that script when sim-lab scenarios are added or renamed.\n"
        f"window.SIM_LAB_SCENARIOS = {body};\n"
    )


def read_scenario_name(unified_json_path):
    """Return meta.name from a unified.json file, or None if unavailable.

    Missing file, invalid JSON, or an absent/blank/malformed meta.name all
    return None; the caller then falls back to the scenario code as the
    display name.
    """
    try:
        with open(unified_json_path, encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError):
        return None
    meta = data.get("meta") if isinstance(data, dict) else None
    name = meta.get("name") if isinstance(meta, dict) else None
    if isinstance(name, str) and name.strip():
        return name.strip()
    return None


def collect_entries(sim_lab_dir):
    """Scan a sim-lab directory and return sorted scenario entries.

    Directories whose names are not valid scenario codes (and any plain files)
    are skipped. A scenario missing meta.name is kept, named by its code, with
    a stderr warning.
    """
    entries = []
    for child in os.listdir(sim_lab_dir):
        path = os.path.join(sim_lab_dir, child)
        if not os.path.isdir(path) or parse_code(child) is None:
            continue
        name = read_scenario_name(os.path.join(path, "unified.json"))
        if name is None:
            sys.stderr.write(f"warning: no meta.name for {child}, using code\n")
        entries.append(build_entry(child, name))
    entries.sort(key=sort_key)
    return entries


def main(argv=None):
    """Generate sim-lab/scenarios.js from the scenarios repo."""
    repo_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description="Generate sim-lab/scenarios.js.")
    parser.add_argument(
        "--scenarios-dir",
        default=str(repo_root.parent / "scenarios"),
        help="Path to the matc-ems/scenarios repo (default: ../scenarios).",
    )
    parser.add_argument(
        "--output",
        default=str(repo_root / "sim-lab" / "scenarios.js"),
        help="Where to write the data file (default: sim-lab/scenarios.js).",
    )
    args = parser.parse_args(argv)

    sim_lab_dir = os.path.join(args.scenarios_dir, "sim-lab")
    if not os.path.isdir(sim_lab_dir):
        sys.stderr.write(f"error: not a directory: {sim_lab_dir}\n")
        sys.exit(1)

    entries = collect_entries(sim_lab_dir)
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_js(entries), encoding="utf-8")
    print(f"Wrote {len(entries)} scenarios to {out_path}")


if __name__ == "__main__":
    main()
