"""Generate sim-lab/scenarios.js from the matc-ems/scenarios repo.

Reads each sim-lab scenario's unified.json for its display name and emits a
committed JS data file that the /sim-lab page renders. Standard library only.

Run from the matc-ems-site repo root:
    python3 scripts/build_sim_lab_index.py [--scenarios-dir ../scenarios]
"""
from __future__ import annotations

import json
import re

# Category letter -> display name (matc-ems/scenarios convention).
CATEGORIES = {
    "B": "Behavioral",
    "C": "Cardiac",
    "M": "Medical",
    "P": "Pediatric",
    "R": "Respiratory",
}

# Scenario folder code: <category letter>-T<tier 1-3>-<sequence digits>.
CODE_RE = re.compile(r"^([BCMPR])-T([123])-(\d+)$")

GITHUB_PAGES_BASE = "https://matc-ems.github.io/scenarios/sim-lab"

# Fixed category display order.
_CATEGORY_ORDER = list(CATEGORIES.values())


def parse_code(folder_name):
    """Parse a scenario folder name into (category_letter, tier, sequence).

    Returns None when the name is not a valid scenario code, so callers can
    skip stray files/directories (e.g. the sim-lab/index.html beside them).
    """
    m = CODE_RE.match(folder_name)
    if not m:
        return None
    letter, tier_digit, seq = m.groups()
    return letter, f"T{tier_digit}", seq


def category_name(letter):
    """Map a category letter to its display name; unknown letters return as-is."""
    return CATEGORIES.get(letter, letter)


def scenario_url(code):
    """The GitHub Pages URL of a scenario's interactive player."""
    return f"{GITHUB_PAGES_BASE}/{code}/"


def build_entry(folder_name, name):
    """Build one scenarios.js entry from a folder name and display name.

    Raises ValueError if folder_name is not a valid scenario code. A falsy
    `name` (None or empty) falls back to the code.
    """
    parsed = parse_code(folder_name)
    if parsed is None:
        raise ValueError(f"not a scenario code: {folder_name!r}")
    letter, tier, _seq = parsed
    return {
        "code": folder_name,
        "category": category_name(letter),
        "tier": tier,
        "name": name or folder_name,
        "url": scenario_url(folder_name),
    }


def sort_key(entry):
    """Sort entries by category (fixed order), then tier, then code."""
    category = entry["category"]
    cat_idx = (
        _CATEGORY_ORDER.index(category)
        if category in _CATEGORY_ORDER
        else len(_CATEGORY_ORDER)
    )
    return (cat_idx, entry["tier"], entry["code"])


def render_js(entries):
    """Render entries as the contents of sim-lab/scenarios.js."""
    body = json.dumps(entries, indent=2, ensure_ascii=False)
    return (
        "// Generated by scripts/build_sim_lab_index.py — do not edit by hand.\n"
        "// Re-run that script when sim-lab scenarios are added or renamed.\n"
        f"window.SIM_LAB_SCENARIOS = {body};\n"
    )
